LnL7/vim-nix

syntax/nix.vim, test/nix.vader
The goal here is to get syntax highlighting to be more correct, adhering more to the AST of the language itself rather than just blindly matching simple patterns or keywords.
However, most toplevel syntactic elements such as function calls (more or less whitespace-separated Nix expressions) currently are matched in a dumb "catch everything and hope it's more or less correct" way rather than following the upstream parser of Nix.
Right now the implementation works "well enough" for all of the Nix expression files I've tested, though I have to admit that my tests were by no means exhaustive but I did test fairly complex Nix expression
files.
In the long run it would be desirable to have a complete set of syntax rules here, so we can also detect errors from just the syntax highlighting rules. …
=> Rewrite of the syntax file

test.nix
This allows to just run `nix-build test.nix` and we get a Vim version with isolated dependencies and just Vader and nothing more.
I've used this mainly because on my setup I'm patching in Vim plugins into the default `vimrc` itself rather than having a dotfile or a system-wide file.
So this should avoid any clashes with existing plugins or the stock Vim initialization file.
=> Add test.nix file to make testing easier with Nix.

syntax/nix.vim, test/nix.vader
Just stumbled over this in a Nix expression file at:
https://github.com/NixOS/nixpkgs/blob/b843e7c50a3e9793625c4ed5af890a58a9620074/nixos/modules/installer/cd-dvd/iso-image.nix#L35
After confirming this with `nix-repl`, it's indeed the case that the `builtins.*` namespace also contains the non-namespaced primops.
The reason why I didn't add `nixSimpleBuiltin` to the `contains=` attribute for `nixBuiltin` is that we want to have the same highlighting as for `nixNamespacedBuiltin`.
=> syntax: Merge non-namespaced+namespaced builtins.

syntax/nix.vim, test/nix.vader
This contains the following fixes and improvements:
* Add highlighting for `assert`.
* Fix highlighting of Nix search paths (`<foo>`).
* Better handling of comments within lookahead/lookbehind
* Remove `and` and `or`, which are not valid in Nix.
* Write a few more tests.
=> More syntax improvements and fixes

syntax/nix.vim, test/nix.vader
So far a search path reference has been a syntax region, which is a very lax match for the strict rules from the actual Nix expression parser and if there is a single `<` operator, the syntax highlighting for the rest of the file is going to be messed up.
Let's turn it into a `syn match` and highlight via the subgroups.
Of course, this also matches the operators we actually want to match, which are `<`, `>`, `<=` and `>=`.
=> syntax: Fix matching < and > operators

test/default.nix
Regression introduced by e7c11195c945747d9323a8afa961d83bbfaf7ec5.
The commit moved the Nix expression file to the test/ subdirectory without changing the reference to the root of the project.
=> test: Fix Nix expression file

README.md
The ~/.vim/bundle directory may not exist. In that case git will check out 
vim-nix right there instead of ~/.vim/bundle/vim-nix
=> README: fix towards foolproofing the instruction

syntax/nix.vim
inline heredoc style makefile breaks string highlighting; this fix adds the `\` in interpolated strings
=> match some specials

syntax/nix.vim, test/nix.vader
This fixes two regular expressions: One very minor (which wasn't really broken but not sufficiently escaped either) in the tests and another one for the `nixAttribute` group.
The main fix/feature this introduces is that it brings back strict matching of string escapes, but instead of only highlighting the valid escapes, the invalid ones now are also highlighted with the `Error` highlighting group.
=> Syntax fixes for string escapes and attributes

indent/nix.vim, test/nix.vader
This adds tests plus a few fixes for indentation, mainly around `let` bindings.
For example things like this should now be indented correctly:
```nix
with import <nixpkgs> {};
let
foo = "bar";
in foo
```
=> A series of indentation fixes

syntax/nix.vim, test/nix.vader
Double dollar signs in Nix strings evaluate to a two dollar
signs rather than a dollar and a string interpolation:
```
Welcome to Nix version 2.1.3. Type :? for help.
nix-repl> ''
$${foo}
''
"$${foo}\n"
```
=> Don't highlight `$${}` as string interpolation

syntax/nix.vim
See https://nixos.org/manual/nix/unstable/expressions/builtins.html for further reference.
=> Highlight `builtins.bit{And,Or,Xor}`

syntax/nix.vim
To reproduce the original issue:
The expression
let
foo = args@{ ... }: args;
in foo
doesn't get highlighted, whereas
let
foo = { ... }@args: args;
in foo
does.
The issue is that `nixArgOperator` should be matchable right in the
cluster `nixExpr` which is used when an assignment in an attr-set or a
`let-in` expression happens. It's ensured that only correct syntax
syntax gets highlighted since `nixArgOperator` requires
`nixFunctionArgument` after that.
cc @Lnl7
=> nixExpr: highlight `args@{ ... }` in an assignment

ftdetect/nix.vim
Hi,
This is kind of hard to explain, and I can't really point to the right location in the docs that explains this, but the TL;DR of this change is:
Enable me to add something like this to my `filetype.vim`
```vim
" Nixpkgs
au BufNewFile,BufRead /var/src/nixpkgs/** setf nix.nixpkgs
```
(While I set some extra settings to `ftplugin/nixpkgs.vim`).
I've learned about this subtlety at https://github.com/neomutt/neomutt.vim/pull/4 .
=> Use setfiletype instead of set filetype

syntax/nix.vim
To demonstrate what I'm talking about:
$ nix repl
Welcome to Nix 2.7.0. Type :? for help.
nix-repl> a = "foo"
nix-repl> "${a}"
"foo"
nix-repl> "''${a}"
"''foo"
nix-repl> "$${a}"
"$${a}"
nix-repl> "\$${a}"
"$foo"
nix-repl> "\${a}"
"${a}"
This change ensures that each expression is highlighted properly in VIM.
The primary issue was that `$${...}` was mistakenly highlighted as
string interpolation.
cc @LnL7
=> syntax: `$${}` is also an escape in simple-string contexts

ftdetect/nix.vim
`flake.lock` is a `json` file.  Let vim know by setting the filetype to `json`
=> Detect flake.lock

syntax/nix.vim
Both are valid Nix 2.4 builtins.
cc @LnL7
=> Highlight `builtins.{floor,ceil}`

syntax/nix.vim
Is perfectly fine to do something like
{ inherit (import <nixpkgs> { }) hello; }
This patch ensures that such an expression is properly highlighted.
=> nixInheritAttributeScope can contain an arbitrary Nix expression

syntax/nix.vim
Although traditionally it should be used as with
lib.attrsets.mapAttrs[1], it's a builtin since Nix 2.1.
https://nixos.org/manual/nixpkgs/unstable/#function-library-lib.attrsets.mapAttrs
=> Add mapAttrs as a builtin.

ftdetect/nix.vim
Nix flakes use lock files named `flake.lock`, which vim currently
interprets as a plain text file. This commit adds an auto command that
sets the `filetype` of files named `flake.lock` to `json`.
=> Interpret flake.lock files as JSON

default.nix, syntax/nix.vim, test/nix.vader
OK I nerdsniped myself into doing that now, damn it :upside_down_face: 
Anyways, this is a draft on purpose, because there's one known case of a wrong highlight (see commit message below) and I haven't tested this under real conditions yet.
cc @LnL7 @figsoda @aszlig 
------
Closes https://github.com/LnL7/vim-nix/issues/41
A few implementation notes:
* `nixInterpolatedPath` is on purpose below `nixPath`, otherwise the
highlighting of top-level expressions, i.e. files containing e.g.
./foo/bar${baz}
break where `$` is entirely unmatched and `{baz}` is misinterpreted as
argument destructuring expression.
* The region's matching behavior now works like this:
First, we expect a path start (i.e. either `~/<further path components>`
or `<path components>`) and then the beginning of a …
=> syntax: correctly highlight paths with interpolation

builtins.sh, syntax/nix.vim
We had quite a bunch of changes in the past that added builtins to get them highlighted properly[1].
Nowadays it's possible to get this from Nix itself by running `nix __dump-language`. This was done on a recent Nix and includes all experimental features by default[2] which seems fine to me since this is not an LSP, but only an approximation.
This patch adds a few new builtins, e.g. `break` and `flakeRefToString` and a script to regenerate the list.
This doesn't include non-scoped builtins (e.g. `map`, `baseNameOf` etc.), but those are added far less frequent, so this seems OK to me.
Also, there are a few hidden builtins, most notably `unsafe*` and `scopedImport`. I think this was done on purpose by upstream and I'm wondering if we should adhere to that approach. If we still want to keep …
=> syntax/nix: autogenerate namespaced builtins from `nix __dump-language`
